name: Deploy and Test

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install make curl -y
    - name: Deploy and Test
      run: |
        make all
